services:
  - type: web
    name: Simulacion-Supremacorte
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && node prisma/seed.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.arlmmzelodckfkjmeuji:simulador32@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - key: DIRECT_URL
        value: postgresql://postgres:simulador32@db.arlmmzelodckfkjmeuji.supabase.co:5432/postgres
      - key: ADMIN_PASSWORD
        value: SCBA_Admin_Profe_2026_#Sec
