services:
  - type: web
    name: corte-demo
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && node prisma/seed.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./dev.db
      - key: ADMIN_PASSWORD
        value: SCBA_Admin_Profe_2026_#Sec
